---
grafana_admin_password: "{{ vault_grafana_admin_password }}"
prometheus_auth_password: "{{ vault_prometheus_auth_password }}"
telegram_bot_token: "{{ vault_telegram_bot_token }}"
telegram_chat_id: "{{ vault_telegram_chat_id }}"
