{
 "title": "CPU USAGE (%)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "RAM USAGE (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (avg by (instance)(node_memory_MemAvailable_bytes) / avg by (instance)(node_memory_MemTotal_bytes))) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM USAGE (MB)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU USAGE (%)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance)(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DISK USAGE ",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_avail_bytes{mountpoint=\"/\"}) / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NETWORK RECEIVED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_network_receive_bytes_total{device!~\"lo|veth.|br.\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NETWORK TRANSMITTED",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by (instance) (irate(node_network_transmit_bytes_total{device!~\"lo|veth.|br.\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CONTAINER STATUS",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(time() - container_last_seen{image!=\"\", name!~\"cadvisor\"}, \"host\", \"$1\", \"instance\", \"cAdvisor-(.*)\")",
     "legendFormat": "{{name}} on {{instance}}"
    }
   ]
  },
  {
   "title": "CONTAINER CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name, instance) (rate(container_cpu_usage_seconds_total{image!=\"\", name!~\"cadvisor\"}[5m])) * 100\r\n",
     "legendFormat": "{{name}} on {{instance}}"
    }
   ]
  },
  {
   "title": "CONTAINER RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, host) (label_replace(container_memory_working_set_bytes{image!=\"\", name!~\"cadvisor\"}, \"host\", \"$1\", \"alias\", \"cAdvisor-(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}